---
- hosts: all
  gather_facts: true
  become: true
  vars_files:
    - vars/default.yml
  tasks:
  # install word press dependecnies
  - name: Install prerequisites
    apt: name=aptitude update_cache=yes state=latest force_apt_get=yes
    tags: [ system ]

  - name: Install LAMP Packages
    apt: name={{ item }} update_cache=yes state=latest
    loop: [ 'apache2', 'mysql-server', 'python3-pymysql', 'php', 'php-mysql', 'libapache2-mod-php' ]
    tags: [ system ]
  
  # download wordpress
  - name: download wordpress
    get_url:
      url: https://wordpress.org/latest.tar.gz
      dest: /tmp/wordpress.tar.gz
  # extract wordpress
  - name: extract wordpress
    unarchive:
      src: /tmp/wordpress.tar.gz
      dest: /var/www/html/
      remote_src: yes
  # set permissions
  - name: set permissions
    file:
      path: /var/www/html/wordpress
      state: directory
      owner: www-data
      group: www-data
      recurse: yes
  # create virtual host
  - name: create virtual host
    template:
      src: /home/ubuntu/project/wordpress/wordpress.conf.j2
      dest: /etc/apache2/sites-available/wordpress.conf

  # enable virtual host
  - name: enable virtual host
    command: a2ensite wordpress.conf
  # disable default virtual host
  - name: disable default virtual host
    command: a2dissite 000-default.conf
  # restart apache
  - name: restart apache
    service:
      name: apache2
      state: restarted
  # create database
  - name: Set the root password
    mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      login_unix_socket: /var/run/mysqld/mysqld.sock
    tags: [ mysql, mysql-root ]

  - name: Remove all anonymous user accounts
    mysql_user:
      name: ''
      host_all: yes
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"
    tags: [ mysql ]

  - name: Remove the MySQL test database
    mysql_db:
      name: test
      state: absent
      login_user: root
      login_password: "{{ mysql_root_password }}"
    tags: [ mysql ]

  - name: Creates database for WordPress
    mysql_db:
      name: "{{ mysql_db }}"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
    tags: [ mysql ]

  - name: Create MySQL user for WordPress
    mysql_user:
      name: "{{ mysql_user }}"
      password: "{{ mysql_password }}"
      priv: "{{ mysql_db }}.*:ALL"
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"
    tags: [ mysql ]
        
        
  # create wp-config.php
  - name: create wp-config.php
    template:
      src: /home/ubuntu/project/wordpress/wp-config.php.j2
      dest: /var/www/html/wordpress/wp-config.php
  # restart apache
  - name: restart apache
    service:
      name: apache2
      state: restarted
  
