pipeline {
    agent any

    parameters {
        choice(name: 'ENVIRONMENT', choices: ['dev', 'test', 'prod'], description: 'Select deployment environment')
        string(name: 'AWS_CREDENTIALS_ID', defaultValue: 'aws1', description: 'AWS Credentials ID in Jenkins')
    }

    environment {
        TERRAFORM_REPO = 'https://github.com/ChowdaryDinesh/DevOps.git'
        APP_REPO = 'https://github.com/ChowdaryDinesh/DevOps.git'
        SSH_PRIVATE_KEY = credentials('aws1_ssh')
        AWS_ACCESS_KEY_ID     = credentials('aws-access-key-id')
        AWS_SECRET_ACCESS_KEY = credentials('aws-secret-access-key')
        AWS_SESSION_TOKEN     = credentials('aws-session-token')
    }

    stages {
        stage('Clone Repositories') {
            steps {
                script {
                    // Clone Terraform code
                    git url: "${env.TERRAFORM_REPO}", branch: 'main'

                    
                }
            }
        }

        stage('Initialize Terraform') {
            steps {
                withCredentials([
                        [ $class: 'StringBinding', credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'],
                        [ $class: 'StringBinding', credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY' ],
                        [ $class: 'StringBinding', credentialsId: 'aws-session-token', variable: 'AWS_SESSION_TOKEN' ]
                    ]) {
                    dir('capstone/ec2_instance') {
                        sh 'terraform init'
                    }
                }
            }
        }

        stage('Apply Terraform') {
            steps {
               withCredentials([
                       [ $class: 'StringBinding', credentialsId: 'aws-access-key-id', variable: 'AWS_ACCESS_KEY_ID'],
                        [ $class: 'StringBinding', credentialsId: 'aws-secret-access-key', variable: 'AWS_SECRET_ACCESS_KEY' ],
                        [ $class: 'StringBinding', credentialsId: 'aws-session-token', variable: 'AWS_SESSION_TOKEN' ]
                    ]) {
                    dir('capstone/ec2_instance') {
                        sh 'terraform apply -auto-approve'
                    }
                }
            }
        }

        stage('Deploy Application') {
            steps {
                script {
                    // Fetch EC2 instance IP from Terraform output
                    def instance_ip = sh(script: 'terraform -chdir=capstone/ec2_instance output -raw public_ip', returnStdout: true).trim()
                    
                    // Connect to EC2 instance and deploy app
                    sh 'chmod 400 capstone/ec2_instance/Key.pem'
                    sh """
                    ssh -i capstone/ec2_instance/Key.pem -o StrictHostKeyChecking=no ubuntu@${instance_ip} << EOF
                        cd /home/ubuntu/DevOps/capstone/sample_python
                        sudo docker-compose -f docker-compose.yml up
                    EOF
                    """
                    sh 'rm ec2-key.pem'
                }
            }
        }
    }

    post {
        always {
            echo 'Pipeline execution completed.'
        }
        success {
            echo 'Pipeline executed successfully.'
        }
        failure {
            echo 'Pipeline execution failed.'
        }
    }
}
