services:
  server:
    build:
      context: .
      dockerfile: DockerFile
    expose:
      - "8000"
  nginx:
    image: nginx:latest
    ports:
      - "8002:8002"  # Map host port 8000 to nginx port 80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - server